export const enum QUERY_KEYS {
  SAMPLE = 'sample',
  SHIFTS = 'shifts',
  SHIFT_DETAIL = 'shift-detail',
  SCREENSHOTS = 'screenshots',
  GRIEVANCES = 'grievances',
  GRIEVANCES_LIST = 'grievances-list',
  GRIEVANCE_DETAIL = 'grievance-detail',
  GRIEVANCE_STATS = 'grievance-stats',
  GRIEVANCE_CLUSTER = 'grievance-cluster',
  GRIEVANCE_TRENDS = 'grievance-trends',
  ANALYTICS = 'analytics',
  MEDIAN = 'median',
  CERTIFICATES = 'certificates',
  ANOMALY = 'anomaly',
  ANOMALY_BATCH = 'anomaly-batch',
  CITY_MEDIAN = 'city-median',
}
