export const enum QUERY_KEYS {
  SAMPLE = 'sample',
  SHIFTS = 'shifts',
  SHIFT_DETAIL = 'shift-detail',
  SCREENSHOTS = 'screenshots',
  GRIEVANCES = 'grievances',
  GRIEVANCES_LIST = 'grievances-list',
  GRIEVANCE_DETAIL = 'grievance-detail',
  GRIEVANCE_STATS = 'grievance-stats',
  GRIEVANCE_CLUSTER = 'grievance-cluster',
  GRIEVANCE_TRENDS = 'grievance-trends',
  SUPPORT_TICKETS = 'support-tickets',
  SUPPORT_TICKET_DETAIL = 'support-ticket-detail',
  SUPPORT_TICKET_STATS = 'support-ticket-stats',
  COMMUNITY_POSTS = 'community-posts',
  COMMUNITY_MY_POSTS = 'community-my-posts',
  COMMUNITY_POST_DETAIL = 'community-post-detail',
  COMMUNITY_PLATFORMS = 'community-platforms',
  COMMUNITY_MODERATION_QUEUE = 'community-moderation-queue',
  ANALYTICS = 'analytics',
  MEDIAN = 'median',
  CERTIFICATES = 'certificates',
  ANOMALY = 'anomaly',
  ANOMALY_BATCH = 'anomaly-batch',
  CITY_MEDIAN = 'city-median',
}
